import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const { prompt } = await request.json();

    if (!prompt || typeof prompt !== "string") {
      return NextResponse.json(
        { error: "Invalid prompt provided" },
        { status: 400 }
      );
    }

    // TODO: Replace this mock generation with a call to your Python backend
    // Example:
    // const response = await fetch('https://your-python-backend.com/generate', {
    //   method: 'POST',
    //   headers: { 'Content-Type': 'application/json' },
    //   body: JSON.stringify({ prompt })
    // });
    // const data = await response.json();
    // return NextResponse.json({ html: data.html });

    // For now, generate a mock HTML based on the prompt
    const html = generateMockLandingPage(prompt);

    return NextResponse.json({ html });
  } catch (error) {
    console.error("Error in generate-landing API:", error);
    return NextResponse.json(
      { error: "Failed to generate landing page" },
      { status: 500 }
    );
  }
}

/**
 * Mock function to generate HTML based on prompt
 * TODO: Replace this entire function with a call to your Python FastAPI backend
 * that uses an LLM to generate the actual HTML
 */
function generateMockLandingPage(prompt: string): string {
  // Extract business name from prompt (simple heuristic)
  const businessMatch = prompt.match(/(?:for|about)\s+(?:a\s+)?([^,\.]+)/i);
  const businessName = businessMatch
    ? businessMatch[1].trim()
    : "Your Business";

  // Extract location if mentioned
  const locationMatch = prompt.match(/in\s+([^,\.]+(?:,\s*[^,\.]+)?)/i);
  const location = locationMatch ? locationMatch[1].trim() : "";

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${businessName} - Generated by CodeCraft AI</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
    body { font-family: 'Inter', sans-serif; }
  </style>
</head>
<body class="bg-white text-gray-900">
  <!-- Navigation -->
  <nav class="fixed w-full bg-white/95 backdrop-blur-sm border-b border-gray-200 z-50">
    <div class="max-w-7xl mx-auto px-6 py-4">
      <div class="flex items-center justify-between">
        <div class="text-2xl font-bold text-emerald-600">${businessName}</div>
        <div class="hidden md:flex items-center gap-8">
          <a href="#features" class="text-gray-600 hover:text-gray-900 transition">Features</a>
          <a href="#benefits" class="text-gray-600 hover:text-gray-900 transition">Benefits</a>
          <a href="#testimonials" class="text-gray-600 hover:text-gray-900 transition">Testimonials</a>
          <a href="#cta" class="px-6 py-2 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 transition">Get Started</a>
        </div>
      </div>
    </div>
  </nav>

  <!-- Hero Section -->
  <section class="pt-32 pb-20 px-6">
    <div class="max-w-7xl mx-auto text-center">
      <h1 class="text-5xl md:text-7xl font-bold mb-6 leading-tight">
        Welcome to <span class="text-emerald-600">${businessName}</span>
      </h1>
      ${location ? `<p class="text-xl text-gray-600 mb-4">Proudly serving ${location}</p>` : ""}
      <p class="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
        ${prompt.substring(0, 150)}...
      </p>
      <div class="flex flex-col sm:flex-row gap-4 justify-center">
        <a href="#cta" class="px-8 py-4 bg-emerald-600 text-white text-lg font-semibold rounded-lg hover:bg-emerald-700 transition">
          Get Started Today
        </a>
        <a href="#features" class="px-8 py-4 border-2 border-gray-300 text-gray-700 text-lg font-semibold rounded-lg hover:border-gray-400 transition">
          Learn More
        </a>
      </div>
    </div>
  </section>

  <!-- Features Section -->
  <section id="features" class="py-20 bg-gray-50 px-6">
    <div class="max-w-7xl mx-auto">
      <h2 class="text-4xl font-bold text-center mb-16">Why Choose Us</h2>
      <div class="grid md:grid-cols-3 gap-8">
        <div class="bg-white p-8 rounded-xl shadow-sm">
          <div class="w-12 h-12 bg-emerald-100 rounded-lg flex items-center justify-center mb-4">
            <svg class="w-6 h-6 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
            </svg>
          </div>
          <h3 class="text-xl font-semibold mb-3">Quality Service</h3>
          <p class="text-gray-600">We deliver exceptional quality in everything we do, ensuring your complete satisfaction.</p>
        </div>
        <div class="bg-white p-8 rounded-xl shadow-sm">
          <div class="w-12 h-12 bg-emerald-100 rounded-lg flex items-center justify-center mb-4">
            <svg class="w-6 h-6 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path>
            </svg>
          </div>
          <h3 class="text-xl font-semibold mb-3">Fast & Reliable</h3>
          <p class="text-gray-600">Quick turnaround times without compromising on quality or attention to detail.</p>
        </div>
        <div class="bg-white p-8 rounded-xl shadow-sm">
          <div class="w-12 h-12 bg-emerald-100 rounded-lg flex items-center justify-center mb-4">
            <svg class="w-6 h-6 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
            </svg>
          </div>
          <h3 class="text-xl font-semibold mb-3">Great Value</h3>
          <p class="text-gray-600">Competitive pricing that delivers outstanding value for your investment.</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Benefits Section -->
  <section id="benefits" class="py-20 px-6">
    <div class="max-w-7xl mx-auto">
      <div class="grid md:grid-cols-2 gap-12 items-center">
        <div>
          <h2 class="text-4xl font-bold mb-6">Experience the Difference</h2>
          <p class="text-lg text-gray-600 mb-6">
            We're committed to providing you with an exceptional experience from start to finish.
          </p>
          <ul class="space-y-4">
            <li class="flex items-start gap-3">
              <svg class="w-6 h-6 text-emerald-600 flex-shrink-0 mt-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
              </svg>
              <span class="text-gray-700">Professional and experienced team</span>
            </li>
            <li class="flex items-start gap-3">
              <svg class="w-6 h-6 text-emerald-600 flex-shrink-0 mt-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
              </svg>
              <span class="text-gray-700">Personalized service tailored to your needs</span>
            </li>
            <li class="flex items-start gap-3">
              <svg class="w-6 h-6 text-emerald-600 flex-shrink-0 mt-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
              </svg>
              <span class="text-gray-700">Satisfaction guaranteed or your money back</span>
            </li>
          </ul>
        </div>
        <div class="bg-gradient-to-br from-emerald-500 to-emerald-700 rounded-2xl p-12 text-white">
          <h3 class="text-3xl font-bold mb-4">Ready to get started?</h3>
          <p class="text-emerald-100 mb-6">Join hundreds of satisfied customers who trust us.</p>
          <a href="#cta" class="inline-block px-8 py-3 bg-white text-emerald-600 font-semibold rounded-lg hover:bg-gray-100 transition">
            Contact Us Now
          </a>
        </div>
      </div>
    </div>
  </section>

  <!-- Testimonials Section -->
  <section id="testimonials" class="py-20 bg-gray-50 px-6">
    <div class="max-w-7xl mx-auto">
      <h2 class="text-4xl font-bold text-center mb-16">What Our Customers Say</h2>
      <div class="grid md:grid-cols-3 gap-8">
        <div class="bg-white p-8 rounded-xl shadow-sm">
          <div class="flex items-center gap-1 mb-4">
            ${Array(5).fill('<svg class="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path></svg>').join('')}
          </div>
          <p class="text-gray-600 mb-4">"Absolutely fantastic service! Exceeded all my expectations and delivered exactly what I needed."</p>
          <p class="font-semibold">Sarah Johnson</p>
          <p class="text-sm text-gray-500">Business Owner</p>
        </div>
        <div class="bg-white p-8 rounded-xl shadow-sm">
          <div class="flex items-center gap-1 mb-4">
            ${Array(5).fill('<svg class="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path></svg>').join('')}
          </div>
          <p class="text-gray-600 mb-4">"Professional, reliable, and a pleasure to work with. Highly recommend to anyone looking for quality."</p>
          <p class="font-semibold">Michael Chen</p>
          <p class="text-sm text-gray-500">Marketing Director</p>
        </div>
        <div class="bg-white p-8 rounded-xl shadow-sm">
          <div class="flex items-center gap-1 mb-4">
            ${Array(5).fill('<svg class="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path></svg>').join('')}
          </div>
          <p class="text-gray-600 mb-4">"Best decision I made for my business. The results speak for themselves!"</p>
          <p class="font-semibold">Emily Rodriguez</p>
          <p class="text-sm text-gray-500">Entrepreneur</p>
        </div>
      </div>
    </div>
  </section>

  <!-- CTA Section -->
  <section id="cta" class="py-20 px-6">
    <div class="max-w-4xl mx-auto text-center">
      <h2 class="text-4xl md:text-5xl font-bold mb-6">Ready to Get Started?</h2>
      <p class="text-xl text-gray-600 mb-8">
        Join us today and experience the difference for yourself.
      </p>
      <form class="max-w-md mx-auto">
        <div class="flex flex-col sm:flex-row gap-4">
          <input 
            type="email" 
            placeholder="Enter your email" 
            class="flex-1 px-6 py-4 border-2 border-gray-300 rounded-lg focus:outline-none focus:border-emerald-500"
          />
          <button 
            type="submit" 
            class="px-8 py-4 bg-emerald-600 text-white font-semibold rounded-lg hover:bg-emerald-700 transition"
          >
            Get Started
          </button>
        </div>
      </form>
      <p class="mt-4 text-sm text-gray-500">No credit card required. Start your free trial today.</p>
    </div>
  </section>

  <!-- Footer -->
  <footer class="bg-gray-900 text-white py-12 px-6">
    <div class="max-w-7xl mx-auto text-center">
      <div class="text-2xl font-bold text-emerald-500 mb-4">${businessName}</div>
      <p class="text-gray-400 mb-6">
        ${location ? `Serving ${location} and beyond` : "Serving customers worldwide"}
      </p>
      <div class="flex justify-center gap-8 mb-6">
        <a href="#" class="text-gray-400 hover:text-white transition">Privacy Policy</a>
        <a href="#" class="text-gray-400 hover:text-white transition">Terms of Service</a>
        <a href="#" class="text-gray-400 hover:text-white transition">Contact</a>
      </div>
      <p class="text-gray-500 text-sm">
        © ${new Date().getFullYear()} ${businessName}. All rights reserved. Generated by CodeCraft AI.
      </p>
    </div>
  </footer>
</body>
</html>
  `.trim();
}
